### ISSUE TITLE
脱壳崩溃了

### ISSUE THREAD

**Issue by godlikewangjun** [CodingGay/BlackDex#110]
**描述错误**
脱壳崩溃了

**重现**
重现该行为的步骤:
脱壳闪剪这个apk

**设备信息**
 - 设备: [小米10]
 - Android版本: [10]

**运行日志**
Unable to instantiate appComponentFactory
                                                                                                    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/user/0/top.niunaijun.blackdexa32/virtual/cache/vm.apk", zip file "/data/user/0/top.niunaijun.blackdexa32/virtual/cache/junit.apk", zip file "/system/framework/org.apache.http.legacy.jar", zip file "/data/app/tv.miaotui.app-RN0E7F5o_ifWYSJZ8II_Ww==/base.apk"],nativeLibraryDirectories=[/data/user/0/top.niunaijun.blackdexa32/virtual/data/app/tv.miaotui.app/lib, /data/app/tv.miaotui.app-RN0E7F5o_ifWYSJZ8II_Ww==/base.apk!/lib/arm64-v8a, /data/user/0/top.niunaijun.blackdexa32/virtual/cache/vm.apk!/lib/arm64-v8a, /data/user/0/top.niunaijun.blackdexa32/virtual/cache/junit.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/product/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.LoadedApk.createAppFactory(LoadedApk.java:256)
                                                                                                    	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:855)
                                                                                                    	at android.app.LoadedApk.getClassLoader(LoadedApk.java:950)
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:1210)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at reflection.MirrorReflection$MethodWrapper.call(MirrorReflection.java:330)
                                                                                                    	at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:192)
                                                                                                    	at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:139)
                                                                                                    	at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:127)
                                                                                                    	at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:65)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7356)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**其他说明**

**Comment by xiaoyaomeng** [comment]
很高兴收到您的邮件，看到后将立即回复~Thank you~

**Comment by wxkly8888** [comment]
同样的错误，请问有解决么
