### ISSUE TITLE
应用dump失败

### ISSUE THREAD

**Issue by hhhaiai** [CodingGay/BlackDex#4]
**描述错误**
解析dumpdex失败，app闪退

**重现**
重现该行为的步骤:
1. dump "流星清理卫士"
2. app闪退

**设备信息**
 - 设备: [谷歌 coral]
 - Android版本: [10]

**运行日志**

```
2021-05-25 10:00:16.206 1999-1999/com.android.systemui D/ImageWallpaper: wallpaper visibility changes to: true
2021-05-25 10:00:16.208 1464-1677/system_process I/ActivityTaskManager: Displayed top.niunaijun.blackdexa32/top.niunaijun.blackbox.proxy.ProxyActivity$P0: +482ms
2021-05-25 10:00:16.212 781-781/? D/Zygote: Forked child process 13408
2021-05-25 10:00:16.217 1464-1679/system_process I/ActivityManager: Start proc 13408:com.meteorandroid.server.ctsclean/u0a129 for added application com.meteorandroid.server.ctsclean
2021-05-25 10:00:16.217 1464-1680/system_process I/libprocessgroup: Successfully killed process cgroup uid 10129 pid 12902 in 42ms
2021-05-25 10:00:16.218 1464-1680/system_process I/libprocessgroup: Successfully killed process cgroup uid 10129 pid 12859 in 0ms
2021-05-25 10:00:16.218 1464-1680/system_process I/libprocessgroup: Successfully killed process cgroup uid 10129 pid 12921 in 0ms
2021-05-25 10:00:16.218 1464-1680/system_process I/libprocessgroup: Successfully killed process cgroup uid 10129 pid 12963 in 0ms
2021-05-25 10:00:16.218 1464-1680/system_process I/libprocessgroup: Successfully killed process cgroup uid 10129 pid 12939 in 0ms
2021-05-25 10:00:16.218 811-811/? D/android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 0
2021-05-25 10:00:16.219 1464-1594/system_process I/ActivityManager: Force stopping com.meteorandroid.server.ctsclean appid=10129 user=0: start instr
2021-05-25 10:00:16.220 1464-1594/system_process I/ActivityManager: Killing 13408:com.meteorandroid.server.ctsclean/u0a129 (adj -10000): stop com.meteorandroid.server.ctsclean
2021-05-25 10:00:16.220 1464-1594/system_process W/ActivityManager: Crash of app com.meteorandroid.server.ctsclean running instrumentation ComponentInfo{com.meteorandroid.server.ctsclean/com.lazarus.LazarusInstrumentation}
2021-05-25 10:00:16.221 1464-1594/system_process I/ActivityManager: Force stopping com.meteorandroid.server.ctsclean appid=10129 user=0: finished inst
2021-05-25 10:00:16.224 1464-1594/system_process I/ActivityManager: Force stopping com.meteorandroid.server.ctsclean appid=10129 user=0: start instr
2021-05-25 10:00:16.224 1464-1594/system_process I/ActivityManager: Killing 0:com.meteorandroid.server.ctsclean/u0a129 (adj -10000): stop com.meteorandroid.server.ctsclean
2021-05-25 10:00:16.224 1464-1594/system_process W/ActivityManager: Crash of app com.meteorandroid.server.ctsclean running instrumentation ComponentInfo{com.meteorandroid.server.ctsclean/com.lazarus.LazarusInstrumentation}
2021-05-25 10:00:16.224 1464-1594/system_process I/ActivityManager: Force stopping com.meteorandroid.server.ctsclean appid=10129 user=0: finished inst
2021-05-25 10:00:16.230 1464-1594/system_process I/ActivityManager: Force stopping com.meteorandroid.server.ctsclean appid=10129 user=0: start instr
2021-05-25 10:00:16.230 1464-1594/system_process I/ActivityManager: Killing 0:com.meteorandroid.server.ctsclean/u0a129 (adj -10000): stop com.meteorandroid.server.ctsclean
2021-05-25 10:00:16.230 1464-1594/system_process W/ActivityManager: Crash of app com.meteorandroid.server.ctsclean running instrumentation ComponentInfo{com.meteorandroid.server.ctsclean/com.lazarus.LazarusInstrumentation}
2021-05-25 10:00:16.230 1464-1594/system_process I/ActivityManager: Force stopping com.meteorandroid.server.ctsclean appid=10129 user=0: finished inst
2021-05-25 10:00:16.235 1464-1680/system_process I/libprocessgroup: Successfully killed process cgroup uid 99052 pid 13237 in 0ms
2021-05-25 10:00:16.235 2283-2283/? I/Zygote: Process 13237 exited due to signal 9 (Killed)
2021-05-25 10:00:16.236 1464-1680/system_process I/libprocessgroup: Successfully killed process cgroup uid 10129 pid 13408 in 0ms
2021-05-25 10:00:16.237 1464-2306/system_process W/Parcel: **** enforceInterface() expected 'android.app.IActivityManager' but read ''
2021-05-25 10:00:16.237 1464-2306/system_process W/Binder: Caught a RuntimeException from the binder stub implementation.
    java.lang.SecurityException: Binder invocation to an incorrect interface
        at android.os.Parcel.nativeEnforceInterface(Native Method)
        at android.os.Parcel.enforceInterface(Parcel.java:623)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2323)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2738)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2021-05-25 10:00:16.237 1464-2306/system_process W/Parcel: **** enforceInterface() expected 'android.app.IActivityManager' but read ''
2021-05-25 10:00:16.237 1464-2306/system_process W/Binder: Caught a RuntimeException from the binder stub implementation.
    java.lang.SecurityException: Binder invocation to an incorrect interface
        at android.os.Parcel.nativeEnforceInterface(Native Method)
        at android.os.Parcel.enforceInterface(Parcel.java:623)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2323)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2738)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2021-05-25 10:00:16.240 781-781/? I/Zygote: Process 13408 exited due to signal 9 (Killed)
2021-05-25 10:00:16.242 1464-1685/system_process E/KernelCpuUidUserSysTimeReader: Negative user/sys time delta for UID=10143
    Prev times: u=22885681061 s=2241507339 Curr times: u=22887115599 s=2241461524
2021-05-25 10:00:16.242 781-781/? D/Zygote: Forked child process 13414
2021-05-25 10:00:16.243 1464-1679/system_process W/ActivityManager: ProcessRecord{8c3d308 0:com.meteorandroid.server.ctsclean/u0a129} start not valid, killing pid=13414, killedByAm=true;No entry in mProcessNames;pendingStart=false;
2021-05-25 10:00:16.243 1464-1679/system_process I/libprocessgroup: Successfully killed process cgroup uid 10129 pid 0 in 0ms
2021-05-25 10:00:16.247 781-781/? D/Zygote: Forked child process 13420
2021-05-25 10:00:16.247 781-781/? I/Zygote: Process 13414 exited due to signal 9 (Killed)
2021-05-25 10:00:16.254 1464-4005/system_process D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=1996, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10129] ], android.os.BinderProxy@5dd7aa1)
2021-05-25 10:00:16.254 1464-4006/system_process D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=1997, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10129] ], android.os.BinderProxy@43074c6)
2021-05-25 10:00:16.254 1464-4005/system_process D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=1998, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10129] ], android.os.BinderProxy@35a3c87)
2021-05-25 10:00:16.254 1464-4380/system_process D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=1999, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10129] ], android.os.BinderProxy@34717b4)
2021-05-25 10:00:16.254 1464-1929/system_process D/ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=1996, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10129] ] (release request)
2021-05-25 10:00:16.255 1464-1929/system_process D/ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=1998, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10129] ] (release request)
2021-05-25 10:00:16.256 781-781/? I/Zygote: Process 12859 exited due to signal 9 (Killed)
2021-05-25 10:00:16.257 1464-1679/system_process W/ActivityManager: ProcessRecord{7b61fdd 0:com.meteorandroid.server.ctsclean/u0a129} start not valid, killing pid=13420, killedByAm=true;No entry in mProcessNames;pendingStart=false;
2021-05-25 10:00:16.258 1464-1679/system_process I/libprocessgroup: Successfully killed process cgroup uid 10129 pid 0 in 0ms
2021-05-25 10:00:16.270 781-781/? D/Zygote: Forked child process 13439
2021-05-25 10:00:16.271 1464-1679/system_process I/ActivityManager: Start proc 13439:com.meteorandroid.server.ctsclean/u0a129 for added application com.meteorandroid.server.ctsclean
2021-05-25 10:00:16.274 781-781/? I/Zygote: Process 13420 exited due to signal 9 (Killed)
2021-05-25 10:00:16.461 1464-1626/system_process I/DropBoxManagerService: add tag=system_server_strictmode isTagEnabled=true flags=0x2
2021-05-25 10:00:16.722 13439-13439/com.meteorandroid.server.ctsclean I/SecondaryDex: Installing secondary dex
2021-05-25 10:00:16.723 13439-13439/com.meteorandroid.server.ctsclean I/SecondaryDex: SecondaryDexExtractor(/data/app/com.meteorandroid.server.ctsclean-PshG7MKbIEKDfOSn8s49Pw==/base.apk, /data/user/0/com.meteorandroid.server.ctsclean/code_cache/secondarydexes)
2021-05-25 10:00:16.724 13439-13439/com.meteorandroid.server.ctsclean I/SecondaryDex: Blocking on lock /data/user/0/com.meteorandroid.server.ctsclean/code_cache/secondarydexes/SecondaryDex.lock
2021-05-25 10:00:16.724 13439-13439/com.meteorandroid.server.ctsclean I/SecondaryDex: /data/user/0/com.meteorandroid.server.ctsclean/code_cache/secondarydexes/SecondaryDex.lock locked
2021-05-25 10:00:16.724 13439-13439/com.meteorandroid.server.ctsclean I/SecondaryDex: SecondaryDexExtractor.load(/data/app/com.meteorandroid.server.ctsclean-PshG7MKbIEKDfOSn8s49Pw==/base.apk, false, )
2021-05-25 10:00:16.726 13439-13439/com.meteorandroid.server.ctsclean I/SecondaryDex: loading existing secondary dex files
2021-05-25 10:00:16.727 13439-13439/com.meteorandroid.server.ctsclean I/SecondaryDex: load found 0 secondary dex files
2021-05-25 10:00:16.727 13439-13439/com.meteorandroid.server.ctsclean I/SecondaryDex: install done
2021-05-25 10:00:16.752 13439-13439/? D/ProcessObserver: onCreate
2021-05-25 10:00:16.757 13439-13439/? I/server.ctsclea: System.exit called, status: 0
2021-05-25 10:00:16.757 13439-13439/? I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
2021-05-25 10:00:16.477 1464-1626/system_process I/DropBoxManagerService: add tag=system_server_strictmode isTagEnabled=true flags=0x2
2021-05-25 10:00:16.767 1464-2316/system_process I/ActivityManager: Process com.meteorandroid.server.ctsclean (pid 13439) has died: fore FGS 
2021-05-25 10:00:16.767 1464-1680/system_process I/libprocessgroup: Successfully killed process cgroup uid 10129 pid 13439 in 0ms
2021-05-25 10:00:16.767 781-781/? I/Zygote: Process 13439 exited cleanly (0)
2021-05-25 10:00:16.768 1464-2316/system_process W/ActivityManager: Crash of app com.meteorandroid.server.ctsclean running instrumentation ComponentInfo{com.meteorandroid.server.ctsclean/com.lazarus.LazarusInstrumentation}
2021-05-25 10:00:16.768 1464-2316/system_process I/ActivityManager: Force stopping com.meteorandroid.server.ctsclean appid=10129 user=0: finished inst
2021-05-25 10:00:23.633 815-930/? D/ASH: @ 487347.463: SensorType 19 resampler quality 0
2021-05-25 10:00:23.633 815-930/? D/ASH: @ 487347.463: SensorType 19 resampler quality 1
2021-05-25 10:00:24.529 815-930/? D/CHRE: @ 487348.351: [ImuCal] Dynamic sensor configuration: high-performance.
2021-05-25 10:00:24.532 815-930/? D/ASH: @ 487348.362: SensorType 1 resampler quality 2
2021-05-25 10:00:31.204 821-861/? D/rlsservice: MonitorDisplayStatus client num 1, display status 1, sensor status 0
2021-05-25 10:00:44.650 602-637/? I/SDM: HWCDisplay::SetActiveConfig: Active configuration changed to: 0
```

**其他说明**

* 附件

https://sanbo.lanzoui.com/iyULupg33fc
密码:24bb

**Comment by hhhaiai** [comment]
![image](https://user-images.githubusercontent.com/5738285/119430771-f113d780-bd43-11eb-8ced-3d918806b8cc.png)
app 特殊在于，只有  库只有armeabi-v7a的

**Comment by hhhaiai** [comment]
`E/.blackdexa32:p: Unknown bits set in runtime_flags: 0x8000`

**Comment by hhhaiai** [comment]
`2021-05-25 10:30:02.500 16426-16432/? A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xf14fea9a in tid 16432 (Binder:16426_2), pid 16426 (monitor)`

**Comment by hhhaiai** [comment]
https://gist.github.com/hhhaiai/612779089049b420503d2166b179108e

**Comment by hhhaiai** [comment]
我去 终于看到完整crash了

https://gist.github.com/hhhaiai/21de7c00d338cf02b5519ec1d346958e
