### ISSUE TITLE
libblackdex.so not found

### ISSUE THREAD

**Issue by ethanhua** [CodingGay/BlackDex#59]
**描述错误**
使用代码编译生成的app进行脱壳时报错

**重现**
重现该行为的步骤:
git clone代码 编译生成apk后安全 对任意apk脱壳处理报错

**设备信息**
 - 设备: 三星s10e
 - Android版本: 10

**运行日志**
```
System.err: java.io.FileNotFoundException: /data/app/top.niunaijun.blackdexa32-7-FpY8hPUlRfMtarwzO1JA==/lib/arm/libblackdex.so: open failed: ENOENT (No such file or directory)
2021-12-19 15:11:07.996 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:496)
2021-12-19 15:11:07.996 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:159)
2021-12-19 15:11:07.996 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at top.niunaijun.blackbox.utils.FileUtils.copyFile(FileUtils.java:247)
2021-12-19 15:11:07.996 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at top.niunaijun.blackbox.core.system.pm.installer.CopyExecutor.exec(CopyExecutor.java:32)
2021-12-19 15:11:07.996 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at top.niunaijun.blackbox.core.system.pm.BPackageInstallerService.installPackageAsUser(BPackageInstallerService.java:46)
2021-12-19 15:11:07.996 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at top.niunaijun.blackbox.core.system.pm.BPackageManagerService.installPackageAsUserLocked(BPackageManagerService.java:617)
2021-12-19 15:11:07.996 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at top.niunaijun.blackbox.core.system.pm.BPackageManagerService.installPackageAsUser(BPackageManagerService.java:492)
2021-12-19 15:11:07.996 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at top.niunaijun.blackbox.core.system.pm.IBPackageManagerService$Stub.onTransact(IBPackageManagerService.java:471)
2021-12-19 15:11:07.996 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at android.os.Binder.execTransactInternal(Binder.java:1056)
2021-12-19 15:11:07.996 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at android.os.Binder.execTransact(Binder.java:1029)
2021-12-19 15:11:07.997 17007-17036/top.niunaijun.blackdexa32 W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
2021-12-19 15:11:07.997 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at libcore.io.Linux.open(Native Method)
2021-12-19 15:11:07.997 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
2021-12-19 15:11:07.997 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
2021-12-19 15:11:07.997 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
2021-12-19 15:11:07.997 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8044)
2021-12-19 15:11:07.997 17007-17036/top.niunaijun.blackdexa32 W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:482)
```

**其他说明**

**Comment by nnjun** [comment]
请先make project一下再安装。
