### ISSUE TITLE
大大们请教个问题，关于修改包名

### ISSUE THREAD

**Issue by Synaric** [CodingGay/BlackDex#73]
前面有issue提到，最新加壳会检测包名，所以我改了包名，app启动正常，但是脱壳时会超时报错。
我看了下没有输出log文件，但是脱壳时logcat有这个报错：

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Application.getApplicationContext()' on a null object reference
        at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:6591)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4227)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8676)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```
github上的release apk是可以正常工作的，我自己改包名编译的apk不行。
全局搜了下，该refactor的都改了，相应的string也替换了，实在找不到问题，求助

**Comment by nnjun** [comment]
内核已许久缺失更新，不支持许多应用了。

**Comment by NPC2000** [comment]
我也同样出现了这种问题，请问一下楼主是怎么解决的？
